services:
  frontend:
    image: awesome/webapp
    networks:
      - front-tier
      - back-tier

  monitoring:
    env_file:
        - a.env
        - b.env
    container_name: monitoring-server
    image: awesome/monitoring
    networks:
      - admin
    expose:
      - 1234
    profiles:
      - tools
      - foo
    cgroup_parent: awesome-parent

  backend:
    networks:
      back-tier:
        aliases:
          - database
      admin:
        aliases:
          - mysql
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: /var/run/postgres/postgres.sock
        target: /var/run/postgres/postgres.sock
    depends_on:
      - monitoring
    extends:
      service: frontend
    ports:
      - name: web-secured
        target: 443
        host_ip: 127.0.0.1
        published: "8083-9000"
        protocol: tcp
        app_protocol: wbsock
        mode : host
    links:
      - "db:database"
    cgroup_parent: awesome-parent
  db:
    image: postgres
    profiles:
      - foo
    devices:
      - "/dev/ttyUSB2:/dev/ttyUSB3"
      - "/dev/sda:/dev/xvda:rwm"

networks:
  front-tier:
  back-tier:
  admin:
volumes:
  db-data:
