name: Submodule Updates

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_submodules:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Submodules
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          parent_repository: ${{ github.repository_owner }}/compose-viz
          checkout_branch: main
          pr_against_branch: main
          owner: ${{ github.repository_owner }}
          label: "automerge"
