name: CRON

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update compose-spec submodule
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive
      - name: Commit changes
        run: |
          git commit -am "chore: update submodules" || echo "No changes to commit."
          git push
